### ISSUE TITLE
Errors in 2018.3

### ISSUE THREAD

**Issue by raghul1129** [joexi/Excel4Unity#2]
Assembly 'Assets/Editor/EPPlus/EPPlus.dll' will not be loaded due to errors:
Unable to resolve reference 'PresentationCore'. Is the assembly missing or incompatible with the current platform?

**Comment by markv12** [comment]
I am also having this issue.

**Comment by joexi** [comment]
resolved

**Comment by VicAMMON** [comment]
Not resolved
